apiVersion: v1
kind: Namespace
metadata:
  name: lab-cmd
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend-nest-cmd
  namespace: lab-cmd
  labels:
    app: backend-nest-cmd
spec:
  replicas: 2
  selector:
    matchLabels:
      app: backend-nest-cmd
  template:
    metadata:
      labels:
        app: backend-nest-cmd
    spec:
      containers:
      - name: backend-nest-cmd
        image: us-west1-docker.pkg.dev/lab-agibiz/docker-repository/backend-nest-cmd
        imagePullPolicy: Always